// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	models "go-tests/models"

	mock "github.com/stretchr/testify/mock"
)

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

// GetById provides a mock function with given fields: id, country
func (_m *Service) GetById(id int, country string) (*models.Category, error) {
	ret := _m.Called(id, country)

	var r0 *models.Category
	var r1 error
	if rf, ok := ret.Get(0).(func(int, string) (*models.Category, error)); ok {
		return rf(id, country)
	}
	if rf, ok := ret.Get(0).(func(int, string) *models.Category); ok {
		r0 = rf(id, country)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Category)
		}
	}

	if rf, ok := ret.Get(1).(func(int, string) error); ok {
		r1 = rf(id, country)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewService creates a new instance of Service. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewService(t interface {
	mock.TestingT
	Cleanup(func())
}) *Service {
	mock := &Service{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
